const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {loadSource}=require('./loadSource.cjs');
const {page,fixtureExtraction}=require('./helpers/extractions.cjs');const {parseEbook,CONTENT_PARSER_VERSION}=loadSource('src/lib/contentParser.ts');const {sentenceSpans}=loadSource('src/lib/sentences.ts');
for(const mode of ['structured','text-only'])test(`parser preservation: ${mode} complete output`,async()=>{const input=fixtureExtraction();if(mode==='text-only')delete input.structuredPages;const result=await parseEbook(input,'fixture.pdf');const expected=JSON.parse(fs.readFileSync(`tests/fixtures/parser-${mode}.json`));expected.diagnostics.parserVersion=CONTENT_PARSER_VERSION;assert.deepEqual(JSON.parse(JSON.stringify(result)),expected);});
for(const mode of ['structured','text-only'])for(const label of ['C H A P T E R 4','Habit 4:'])test(`chapter correction: ${mode} ${label}`,async()=>{const pages=[page(0,[{text:label,fontSize:24},{text:'A Different Perspective',fontSize:24},'A gardener learns a useful lesson in the orchard. A second sentence explains the idea.'])];const result=await parseEbook({pages:pages.map(p=>p.text),structuredPages:mode==='structured'?pages:[]},'garden.pdf');assert.ok(result.chapters.some(c=>c.kind==='chapter'&&c.pageIndex===0&&/4/.test(c.title)));assert.ok(result.paragraphs.some(t=>t.includes('A gardener learns')));});
for(const mode of ['structured','text-only'])test(`chapter correction: ${mode} unlabeled contents and malformed leaders`,async()=>{const texts=['Part I\nOrchard Lessons ���� 1\nRiver Lessons ���� 3\nMountain Lessons ���� 5\nForest Lessons ���� 7','Orchard Lessons\nA gardener studies the fruit trees carefully. Her apprentice writes down the observations.','The orchard grows across the valley. Each tree bears a different fruit.','River Lessons\nThe carpenter replaces a broken wooden bridge. His apprentice helps carry the heavy boards.','They work until the afternoon. The river flows underneath them.','Mountain Lessons\nA traveler follows the steep mountain path. The air becomes cooler with each step.','He reaches the cabin at sunset. His guide prepares a warm meal.','Forest Lessons\nA teacher leads her students through the ancient forest. The children notice several unfamiliar birds.'];const pages=texts.map((text,i)=>page(i,text.split('\n').map((text,j)=>j===0?{text,fontSize:22}:text)));const result=await parseEbook({pages:texts,structuredPages:mode==='structured'?pages:[]},'lessons.pdf');assert.ok(!result.chapters.some(c=>c.kind==='part'&&c.pageIndex===0));for(const i of [1,3,5,7])assert.ok(result.chapters.some(c=>c.pageIndex===i&&c.kind==='chapter'),`destination ${i}`);assert.equal(result.paragraphPages[result.readingStart],1);});
const sentences=[['“Wait...” She stopped. “What?!” He ran.',4],['Dr. Smith met J. R. Jones at 3.14 meters. Another sentence follows.',2],['She paused . . . then spoke. Another sentence follows.',2],['🧬 “Really?” she asked. Another sentence follows.',2]];
for(const [text,count] of sentences)for(const native of [false,true])test(`production sentences: ${text} native=${native}`,async()=>{const pages=[page(0,[{text:'Chapter One',fontSize:24},text])];const parsed=await parseEbook({pages:pages.map(p=>p.text),structuredPages:pages},'book.pdf',native?async texts=>texts.map(t=>sentenceSpans(t).map(s=>s.start+s.text.length)):undefined);assert.equal(parsed.readingUnits.reduce((n,u)=>n+u.sentenceCount,0),count);assert.ok(parsed.readingUnits.every(u=>u.sentenceCount<=2));assert.ok(parsed.paragraphs.join(' ').includes('Another sentence follows.')||parsed.paragraphs.join(' ').includes('He ran.'));});
test('production sentences: pages join continuously, chapters do not share cards, final sentence stands alone',async()=>{const pages=[page(0,[{text:'Chapter One',fontSize:24},'A thought continues']),page(1,['onto another page. A second sentence follows. A last sentence ends.']),page(2,[{text:'Chapter Two',fontSize:24},'A different chapter begins. Another sentence follows.'])];const parsed=await parseEbook({pages:pages.map(p=>p.text),structuredPages:pages},'book.pdf');assert.ok(parsed.paragraphs.includes('A thought continues onto another page. A second sentence follows.'));assert.ok(parsed.paragraphs.includes('A last sentence ends.'));assert.ok(parsed.readingUnits.every(u=>u.sentences.length===u.sentenceCount));});
test('production sentences: native tokenizer failure uses deterministic fallback',async()=>{const input=fixtureExtraction();assert.deepEqual(await parseEbook(input,'book.pdf',async()=>{throw Error('old binary');}),await parseEbook(input,'book.pdf'));});
