import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1 },
  reader: { flex: 1 },
  list: { flex: 1 },
  page: { flexShrink: 0, width: '100%', overflow: 'hidden', paddingBottom: 76, paddingHorizontal: 30, paddingTop: 70 },
  textContainer: { flex: 1, width: '100%' },
  textScrollContent: { flexGrow: 1 },
  textPressable: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 12 },
  paragraph: {
    fontFamily: 'Georgia',
    letterSpacing: 0.1,
    maxWidth: 700,
    width: '100%',
  },
  topChrome: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 18,
    position: 'absolute',
    right: 18,
    top: 10,
  },
  chromeActions: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  roundControl: {
    alignItems: 'center',
    borderRadius: 19,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  controlPressed: { opacity: 0.6, transform: [{ scale: 0.96 }] },
  backGlyph: { fontSize: 36, fontWeight: '300', lineHeight: 37, marginTop: -3 },
  settingsGlyph: { fontFamily: 'Georgia', fontSize: 15, fontWeight: '700' },
  chaptersGlyph: { fontSize: 18, fontWeight: '700' },
  contextGlyph: { fontFamily: 'Georgia', fontSize: 21, fontWeight: '700' },
  chromeTitleBlock: { flex: 1, marginHorizontal: 12 },
  chromeTitle: { fontSize: 13, fontWeight: '700', textAlign: 'center' },
  chromeChapter: { fontSize: 11, lineHeight: 15, fontWeight: '600', marginTop: 2, textAlign: 'center' },
  chapterMeta: { fontSize: 12, marginTop: 4, marginBottom: 4 },
  settingsPanel: {
    borderRadius: 24,
    borderWidth: 1,
    bottom: 16,
    left: 16,
    padding: 20,
    position: 'absolute',
    right: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
  },
  chapterPanel: {
    borderRadius: 24,
    borderWidth: 1,
    bottom: 16,
    left: 16,
    maxHeight: '72%',
    padding: 20,
    position: 'absolute',
    right: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
  },
  contextPanel: {
    borderRadius: 24,
    borderWidth: 1,
    bottom: 16,
    left: 16,
    maxHeight: '66%',
    padding: 20,
    position: 'absolute',
    right: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
  },
  chapterList: { marginTop: 12 },
  chapterRow: { borderBottomColor: '#E5E1E9', borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 14 },
  chapterTitle: { fontSize: 16, fontWeight: '600', lineHeight: 22 },
  noChapters: { fontSize: 15, paddingVertical: 18 },
  startReadingRow: { borderBottomColor: '#E5E1E9', borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 14 },
  startReadingTitle: { fontSize: 16, fontWeight: '700' },
  startReadingBody: { fontSize: 12, marginTop: 3 },
  settingsHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  settingsTitle: { fontSize: 17, fontWeight: '700' },
  doneButton: { fontSize: 14, fontWeight: '600' },
  sizeRow: { alignItems: 'center', flexDirection: 'row', gap: 14, marginTop: 18 },
  sizeButton: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    flex: 1,
    height: 48,
    justifyContent: 'center',
  },
  sizeSmall: { fontFamily: 'Georgia', fontSize: 16 },
  sizeLarge: { fontFamily: 'Georgia', fontSize: 24 },
  sizeValue: { fontSize: 12, fontVariant: ['tabular-nums'], width: 24, textAlign: 'center' },
  themeRow: { flexDirection: 'row', gap: 12, marginTop: 20 },
  themeOption: { alignItems: 'center', flex: 1, gap: 6 },
  themeSwatch: {
    alignItems: 'center',
    borderRadius: 12,
    height: 50,
    justifyContent: 'center',
    width: '100%',
  },
  themeLetters: { fontFamily: 'Georgia', fontSize: 18, fontWeight: '700' },
  themeLabel: { fontSize: 11, fontWeight: '600' },
  supplementRow: { borderBottomColor: '#E5E1E9', borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 13 },
  supplementKind: { fontSize: 11, fontWeight: '800', letterSpacing: 0.8, textTransform: 'uppercase' },
  supplementText: { fontFamily: 'Georgia', fontSize: 15, lineHeight: 22, marginTop: 5 },
  improveButton: { borderRadius: 13, borderWidth: 1, justifyContent: 'center', marginTop: 18, minHeight: 58, paddingHorizontal: 14 },
  improveTitle: { fontSize: 14, fontWeight: '700' },
  improveBody: { fontSize: 11, marginTop: 3 },
});
