const {loadSource}=require('../loadSource.cjs');
const {createRenderer,nativeMock,settle,deferred}=require('./render.cjs');
const {makeSourceAnchor}=loadSource('src/lib/readingUnits.ts');
const paragraphs=['The gardener crossed the ancient orchard before sunrise. Her basket held a collection of ripe apples.', 'Beside the river a carpenter repaired the broken wooden bridge. His apprentice brought fresh planks from the workshop.', 'An astronomer watched the distant planets through her telescope. A colleague recorded each observation in a notebook.'];
function sample(id='a',extra={}) {
 const readingUnits=paragraphs.map((text,i)=>({id:`unit-${i}`,text,sentenceCount:2,anchor:makeSourceAnchor(i,undefined,0,text.length,text),endAnchor:makeSourceAnchor(i,undefined,0,text.length,text),sourcePages:[i],wordCount:text.split(' ').length,supplementIds:[],sentences:[]}));
 const content={pdfUri:`file:///old/${id}.pdf`,paragraphs:[...paragraphs],paragraphPages:[0,1,2],chapters:[],readingStart:0,readingUnits,chapterVersion:4,parserVersion:9,layoutRevision:'original',metadata:{title:{value:'A Garden',confidence:1,evidence:[]},authors:[]},sections:[],blocks:[],supplements:[],...extra};
 const summary={id,title:'A Garden',originalFileName:'garden.pdf',importedAt:'2026-09-14T00:00:00Z',paragraphCount:3,currentParagraph:0,currentAnchor:readingUnits[0].anchor};
 return {content,summary};
}
async function appHarness(options={}) {
 const renderer=createRenderer(), native=nativeMock(), alerts=[], scheduled=[], files=new Set(options.files??[]), calls={extract:[],content:[],chapter:[],deleted:[],library:[]};
 const samples=options.samples??[sample(),sample('b')];const data=new Map(samples.map(s=>[s.summary.id,structuredClone(s.content)]));let library=samples.map(s=>structuredClone(s.summary));
 const storage={loadLibrary:async()=>library,loadPreferences:async()=>({fontSize:24,theme:'paper'}),loadBookContent:async id=>options.load?options.load(id,data):data.get(id),persistLibrary:async books=>{calls.library.push(books);library=structuredClone(books);},persistPreferences:async()=>{},storeBook:async book=>{const {id,title,originalFileName,importedAt,lastReadAt,paragraphCount,currentParagraph,currentAnchor,readingProgress,currentSourcePage,parseConfidence,...content}=book;data.set(id,content);return {id,title,originalFileName,importedAt,lastReadAt,paragraphCount,currentParagraph,currentAnchor,readingProgress,currentSourcePage,parseConfidence,readingStart:book.readingStart,parserVersion:book.parserVersion};},storeBookContent:async(id,content)=>{calls.content.push({id,content});await options.save?.(id,content);data.set(id,structuredClone(content));},storeChapterMetadata:async(id,content)=>{calls.chapter.push({id,content});await options.chapterSave?.(id,content);},deleteBookData:async id=>{calls.deleted.push(id);data.delete(id);},};
 native.Alert.alert=(...args)=>alerts.push(args);
 const parser=loadSource('src/lib/contentParser.ts');
 const mocks={react:renderer.react,'react-native':native,'expo-document-picker':{getDocumentAsync:async()=>({assets:[{uri:'file:///import.pdf',name:'garden.pdf'}]})},'expo-file-system':{Paths:{document:'file:///new'},Directory:class{constructor(...parts){this.uri=parts.map(p=>p.uri??p).join('/');}create(){}},File:class{constructor(...parts){this.uri=parts.map(p=>p.uri??p).join('/');}get exists(){return files.has(this.uri);}async copy(destination){files.add(destination.uri);}delete(){files.delete(this.uri);}}},'src/components/LibraryScreen.tsx':{LibraryScreen:'Library'},'src/components/ReaderScreen.tsx':{ReaderScreen:'Reader'},'src/lib/storage.ts':storage,'src/lib/contentParser.ts':{...parser,parseEbook:options.parse??(async()=>structuredClone(samples[0].content))},'modules/pdf-text-extractor/src/PDFTextExtractorModule.ts':{extract:async uri=>{calls.extract.push(uri);return options.extract?options.extract(uri):{pages:paragraphs,outlines:[]};}},$globals:{setTimeout:f=>{scheduled.push(f);return scheduled.length;}}};
 renderer.mount(loadSource('App.tsx',mocks).default);await settle();renderer.render();await settle();
 const find=type=>renderer.nodes().find(n=>n.type===type)?.props;
 return {calls,data,alerts,files,renderer,storage,library:()=>library,reader:()=>find('Reader'),screen:()=>find('Library'),async open(id='a'){await find('Library').onOpenBook(library.find(b=>b.id===id));await settle();},async remove(id='a'){find('Library').onDeleteBook(library.find(b=>b.id===id));alerts.at(-1)[2].find(a=>a.text==='Remove').onPress();await settle();},async timers(){scheduled.splice(0).forEach(f=>f());await settle();},settle};
}
module.exports={sample,appHarness,deferred,settle};
